import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/theme-selector";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`min-h-dvh flex flex-col ${geistSans.variable} ${geistMono.variable} font-mono bg-background text-foreground`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="flex justify-around items-center px-6 py-4 h-16 border-b border-border bg-background-secondary">
              {/* Logo/Navegación principal */}
              <div className="flex items-center gap-6">
                <Link href="/dashboard">
                  <span className="text-lg font-bold text-foreground hover:text-muted-foreground transition-colors duration-200 cursor-pointer">
                    Risuto
                  </span>
                </Link>

                {/* Navegación solo para usuarios logueados */}
                <SignedIn>
                  <nav className="flex items-center gap-4 text-foreground">
                    <span className="hover:text-muted-foreground transition-colors duration-200 cursor-pointer">Books</span>
                    <span className="hover:text-muted-foreground transition-colors duration-200 cursor-pointer">Lists</span>
                  </nav>
                </SignedIn>
              </div>

              {/* Botones de sesión y modo */}
              <div className="flex items-center gap-4">
                <ModeToggle />
                <SignedOut>
                  <SignInButton mode="modal" />
                  <SignUpButton mode="modal" />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </header>

            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
